name: assurapp
description: "Assur.App Mobile for Experts"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  http: ^1.2.0
  http_parser: ^4.0.2
  jwt_decode: ^0.3.1
  image_picker: ^1.0.7
  uuid: ^4.3.3
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  path: ^1.8.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/assurapp.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/