name: AssurApp Dev
environment: development
server:
  port: 8000
  tomcat:
    max-http-form-post-size: 100MB
spring:
  mail:
    port: 9025
    host: localhost
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  
  datasource:
    url: jdbc:postgresql://localhost:5432/assurapp
    username: assurapp
    password: assurapp
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect