name: AssurApp Dev
environment: development
server:
  port: 8000
spring:
  mail:
    port: 9025
    host: localhost
  datasource:
    url: jdbc:postgresql://localhost:5433/assurapp
    username: assurapp
    password: assurapp
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

---

name: AssurApp Test
environment: testing
server:
  port: 9000
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:assurapp
    username: assurapp
    password: assurapp
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  properties:
    hibernate:
      database-platform: org.hibernate.dialect.H2Dialect
