name: AssurApp Dev
environment: development
server:
  port: 8000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/assurapp
    username: assurapp
    password: assurapp
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
