name: AssurApp Dev
environment: development
server:
  port: 8000
spring:
  mail:
    port: 9025
    host: localhost

  datasource:
    url: jdbc:postgresql://localhost:5433/assurapp
    username: assurapp
    password: assurapp
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect