export enum InsuranceType {
  CAR = "CAR",
  LIFE = "LIFE",
  HEALTH = "HEALTH",
  HOME = "HOME",
  TRAVEL = "TRAVEL",
  PET = "PET",
  BUSINESS = "BUSINESS",
  LIABILITY = "LIABILITY",
  DISABILITY = "DISABILITY",
  RENTERS = "RENTERS"
}
