version: '3.9'
services:
  assurapp-db:
    image: postgres:16.0
    container_name: assurapp-db
    environment:
      - POSTGRES_DB=assurapp
      - POSTGRES_PASSWORD=assurapp
      - POSTGRES_USER=assurapp
    ports:
      - 5431:5432
      - 5432:5432
      - 5433:5432
  assurapp-smtp:
    container_name: assurapp-smtp
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - 9080:80
      - 9025:25
      - 9143:143