version: '3.9'
services:
  assurapp-db:
    image: postgres:16.0
    container_name: assurapp-db
    environment:
      - POSTGRES_DB=assurapp
      - POSTGRES_PASSWORD=assurapp
      - POSTGRES_USER=assurapp
    ports:
      - 5433:5432
  assurapp-kc:
    image: keycloak/keycloak:22.0
    container_name: assurapp-kc
    command: ["start-dev"]
    environment:
      - KEYCLOAK_DATABASE_HOST=assurapp-db
      - KEYCLOAK_DATABASE_NAME=assurapp
      - KEYCLOAK_DATABASE_USER=assurapp
      - KEYCLOAK_DATABASE_PASSWORD=assurapp
      - KEYCLOAK_ADMIN=assurapp
      - KEYCLOAK_ADMIN_PASSWORD=assurapp
      - KEYCLOAK_DATABASE_SCHEMA=kc-db
    ports:
      - 8080:8080
  assurapp-smtp:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - 9080:80
      - 9025:25
      - 9143:143