name: Java CI

on:
  push:
    branches:
      - main
      - develop
jobs:
   deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('assurapp-api/**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Clean up Docker cache 
      run: docker builder prune -a -f

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: assurapp-api/.
        dockerfile: Dockerfile
        push: true
        tags: ${{secrets.DOCKER_USERNAME}}/assurapp:latest
